apiVersion: v1
kind: Pod
spec:
  volumes:
    - name: data
      awsElasticBlockStore:
        volumeID: <volume_ID>
        fsType: ext4
  containers:
  - name: my-app
    image: someimage
    volumeMounts:
      - name: data # Reference "data" Volume
        mountPath: /data/storage