apiVersion: v1
kind: Pod
metadata:
        name: busybox-liveness-pod
spec:
        containers:
        - name: busybox-liveness-pod
          image: k8s.gcr.io/busybox
          resources:
            limits:
              memory: "64Mi" # 64 MB
              cpu: "50m" # 50 millicpu (.05 cpu or 5% of the cpu)
          args:
          - /bin/sh
          - -c
          - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
          livenessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5
