apiVersion: v1
kind: Pod
metadata:
  name: nginx-alpine-volume
spec:
  volumes:
    - name: html # Define Initial Volume 
      emptyDir: {} # Lifetime of the Pod
  containers:
  - name: nginx
    image: nginx:alpine
    volumeMounts:
      - name: html # Reference "html" Volume
        mountPath: /usr/share/nginx/html
        readOnly: true
  - name: html-updater
    image: alpine
    command: ["bin/sh","-c"]
    args: # updates latest date every 10 sec
      - while true; do date >> /html/index.html;
          sleep 10; done
    volumeMounts:
      - name: html # Reference "html" Volume
        mountPath: /html