apiVersion: v1
kind: Pod
metadata:
  name: docker-volume
spec:
  volumes:
    - name: docker-socket # Define a socket volume
      hostPath: # on host
        path: /var/run/docker.sock
        type: Socket
  containers:
  - name: docker
    image: docker
    command: ["sleep"]
    args: ["100000"]
    volumeMounts:
      - name: docker-socket # Reference "html" Volume
        mountPath: /usr/share/nginx/html